// Package store keeps request records: a summary list in memory (and in an
// append-only index.jsonl), and one detail file per request with the bodies.
//
// Plain files instead of a database keep the binary dependency-free, and a
// request log is append-only anyway.
package store

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/JimmyWesley/rlcd-gateway/gateway/internal/ir"
)

type Usage struct {
	InputTokens         int `json:"input_tokens"`
	OutputTokens        int `json:"output_tokens"`
	CacheReadTokens     int `json:"cache_read_input_tokens"`
	CacheCreationTokens int `json:"cache_creation_input_tokens"`
}

// Record is the summary of one proxied call.
type Record struct {
	ID       string    `json:"id"`
	Time     time.Time `json:"time"`
	Method   string    `json:"method"`
	Path     string    `json:"path"`
	Route    string    `json:"route"`
	Upstream string    `json:"upstream"`
	// ClientModel is what the agent asked for; Model is what was actually sent.
	ClientModel string `json:"client_model,omitempty"`
	Model       string `json:"model,omitempty"`
	AuthMode    string `json:"auth_mode"` // oauth | api-key | none, as seen from the client
	Stream      bool   `json:"stream"`
	Status      int    `json:"status"`
	TTFBMs      int64  `json:"ttfb_ms"`
	DurationMs  int64  `json:"duration_ms"`
	// EstTokens is our estimate of the request as the client sent it.
	EstTokens int            `json:"est_tokens"`
	ByKind    map[string]int `json:"by_kind,omitempty"`
	Usage     *Usage         `json:"usage,omitempty"`
	// StrippedThinking counts thinking blocks removed when crossing providers.
	StrippedThinking int    `json:"stripped_thinking,omitempty"`
	Error            string `json:"error,omitempty"`
	// ConversationID groups the turns of one agent session.
	ConversationID string `json:"conversation_id,omitempty"`
	// RouteReason explains the route choice when a router made it.
	RouteReason string `json:"route_reason,omitempty"`
	// Stages holds each pipeline stage's small summary, keyed by stage name.
	Stages map[string]json.RawMessage `json:"stages,omitempty"`
	// StageErrors records stages that failed and were skipped.
	StageErrors map[string]string `json:"stage_errors,omitempty"`
}

// Detail is everything kept about one call, loaded on demand.
type Detail struct {
	Record
	RequestHeaders map[string]string `json:"request_headers"`
	XRay           *ir.Request       `json:"xray,omitempty"`
	// StageDetails holds each stage's large report (e.g. the pruning diff).
	StageDetails map[string]json.RawMessage `json:"stage_details,omitempty"`
	// SentBody is what was actually forwarded, when a stage changed it.
	SentBody     string `json:"sent_body,omitempty"`
	RequestBody  string `json:"request_body,omitempty"`
	ResponseBody string `json:"response_body,omitempty"`
}

const keepInMemory = 500

type Store struct {
	dir    string
	mu     sync.RWMutex
	recent []Record
	subs   map[chan Record]struct{}
}

func Open(dir string) (*Store, error) {
	if err := os.MkdirAll(filepath.Join(dir, "requests"), 0o700); err != nil {
		return nil, err
	}
	s := &Store{dir: dir, subs: map[chan Record]struct{}{}}
	s.loadIndex()
	return s, nil
}

func (s *Store) loadIndex() {
	f, err := os.Open(filepath.Join(s.dir, "index.jsonl"))
	if err != nil {
		return
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		var r Record
		if json.Unmarshal(sc.Bytes(), &r) == nil {
			s.recent = append(s.recent, r)
		}
	}
	if len(s.recent) > keepInMemory {
		s.recent = s.recent[len(s.recent)-keepInMemory:]
	}
}

// Save persists a finished call and notifies live subscribers.
func (s *Store) Save(d *Detail) error {
	b, err := json.Marshal(d)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(s.dir, "requests", d.ID+".json"), b, 0o600); err != nil {
		return err
	}
	line, _ := json.Marshal(d.Record)
	f, err := os.OpenFile(filepath.Join(s.dir, "index.jsonl"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	_, err = f.Write(append(line, '\n'))
	f.Close()

	s.mu.Lock()
	s.recent = append(s.recent, d.Record)
	if len(s.recent) > keepInMemory {
		s.recent = s.recent[len(s.recent)-keepInMemory:]
	}
	for ch := range s.subs {
		select {
		case ch <- d.Record:
		default: // a slow dashboard tab must never block the proxy
		}
	}
	s.mu.Unlock()
	return err
}

// Recent returns summaries, newest first.
func (s *Store) Recent() []Record {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]Record, len(s.recent))
	for i, r := range s.recent {
		out[len(s.recent)-1-i] = r
	}
	return out
}

func (s *Store) Get(id string) (*Detail, error) {
	// ids are generated by us (hex), but never trust a path segment.
	if filepath.Base(id) != id {
		return nil, os.ErrNotExist
	}
	b, err := os.ReadFile(filepath.Join(s.dir, "requests", id+".json"))
	if err != nil {
		return nil, err
	}
	var d Detail
	return &d, json.Unmarshal(b, &d)
}

func (s *Store) Subscribe() (chan Record, func()) {
	ch := make(chan Record, 32)
	s.mu.Lock()
	s.subs[ch] = struct{}{}
	s.mu.Unlock()
	return ch, func() {
		s.mu.Lock()
		delete(s.subs, ch)
		s.mu.Unlock()
	}
}
